In [1]:
name="RAMU"
age=19
cgpa=8.56
print(name)
print(age)
print(cgpa)

RAMU
19
8.56


In [2]:
a=int(input("ENTER NUMBER 1:"))
b=int(input("ENTER NUMBER 2:"))
c=a+b
d=a-b
e=a*b
f=a/b
print(c)
print(d)
print(e)
print(f)

ENTER NUMBER 1: 5
ENTER NUMBER 2: 1


6
4
5
5.0


In [6]:
marks=int(input("ENTER STUDENT'S MARKS:"))
if marks>=90:
  print("EXCELLENT")
elif marks>=75 and marks<=89:
  print("VERY GOOD")
elif marks>=60 and  marks<=74:
  print("GOOD")
else:
  print("NEEDS IMPROVEMENT")
    


ENTER STUDENT'S MARKS: 95


EXCELLENT


In [7]:
marks=[78,85,92,67,88]
total=sum(marks)
average=sum(marks)/len(marks)
Maximum=max(marks)
Minimum=min(marks)
print(total)
print(average)
print(Maximum)
print(Minimum)

410
82.0
92
67


In [15]:
def calculate_average(numbers):
  average=sum(numbers)/len(numbers)
  return average
result=calculate_average([78,85,92,67,88])
print(result)
    

82.0


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [17]:
print(type(arr))

<class 'numpy.ndarray'>


In [18]:
print(arr[0])
print(arr[2])
print(arr[4])

1
3
5


In [19]:
print(arr[1:4])


[2 3 4]


In [39]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
print(arr)
print(arr[0])
print(arr[5])
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30 40 50 60]
10
60
(6,)
1
6


In [37]:
marks = np.array([78, 85, 92, 67, 88])
total=sum(marks)
average=sum(marks)/len(marks)
Maximum=max(marks)
Minimun=min(marks)
print(total)
print(average)
print(Maximum)
print(Minimum)


410
82.0
92
67


In [24]:
a = np.array([1, 2, 3, 4, 5])
print(a+10)
print(a*2)
print(a ** 2)


[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [35]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])  
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr[0][0],arr[0][1],arr[0][2])
print(arr[0][1],arr[1][1])
print(arr[1][1])
print(arr[1,2])


(2, 3)
2
6
10 20 30
20 50
50
60


In [33]:
hours = np.array([2, 4, 5, 7, 8])
marks = np.array([40, 50, 55, 70, 80])
averagehours=sum(hours)/len(hours)
averagemarks=sum(marks)/len(marks)
Maximummarks=max(marks)
Minimummarks=min(marks)
print(averagehours)
print(averagemarks)
print(Maximummarks)
print(Minimummarks)

5.2
59.0
80
40


In [ ]:
#PANDAS 
import pandas as pd
data={
    "Name":["A","B","C","D"],
    "Age":[20,19,21,22],
    "Hours":[2,3,5,6],
    "Marks":[75,82,90,95]
}
df=pd.DataFrame(data)
print(df) # will return the entire table
print(df.head(2)) # will return the table values from top 
print(df.tail(2))   # will return the table values from bottom 
print(df.shape) # will return the rows and columns number
print(df.columns)  # will return the nmaes of the columns
print(df.dtypes) # will return the datatypes of columns 
print(df.info())  # will return the information about table like names of columns ,no.of non-null vales etc
print(df.describe()) # will describe the statistical information about tables 
print(df["Marks"])  # will return the name and datatype of the marks
print(df[["Age","Marks"]])
print(df[["Marks"]])
print(df.iloc[0])   # will return the first row 
print(df.iloc[0:2])  # will return from row 0 to 1
print(df.iloc[2,3])   # will return a specific indexed value
print(df.loc[0,"Marks"]) # will return the o row value in MArks column
print(df[df["Marks"]>60])  # add condition with tables 
print( df[(df["Marks"]>70) & (df["Age"]>20)])   # add  multiple condition with tables
df["Passed"]=df["Marks"]>85 # to add a new column
# to work with  basic statistics
print(df["Marks"].mean())
print(df["Marks"].min())
print(df["Marks"].max())
print(df["Marks"].sum()) 
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 21, 19, 22, 20],
    "Hours": [2, 4, 5, 7, 8],
    "Marks": [40, 50, 55, 70, 80]
}

df = pd.DataFrame(data)
print(df)
print(df.iloc[0:4])
print(df.iloc[3:5])
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())
print(df.describe())
print(df[["Marks"]])
print(df[["Marks","Age"]])
print(df.iloc[3:4])
print(df.iloc[4,3])
print(df[df["Marks"]>60])
print(df[df["Marks"]<60])
print(df[df["Hours"]>=5])
print(df["Marks"].mean())
print(df["Marks"].max())
print(df["Marks"].min())
print(df["Marks"].sum())
X = df[["Age", "Hours"]]
y = df["Marks"]
print(X)
print(y)
df["Passed"]=df["Marks"]>=40
print(df)

In [ ]:
import pandas as pd
df=pd.read_csv("students.csv)")

In [ ]:
# loading csv files
import pandas as pd
#df=pd.read_csv("filename.csv")
# CREATING A MESSY DATASET
data = {
    "Name": ["A", "B", "C", "D", "E", "E"],
    "Age": [20, 21, None, 22, 20, 20],
    "Hours": [2, 4, 5, None, 8, 8],
    "Marks": [40, 50, 55, 70, None, None]
}

df = pd.DataFrame(data)

print(df)
print(df.isnull())  # to check the null values in the dataset
print(df.isnull().sum())  # to check the number of null values in each column
print(df.isna())  # to check the null values in the dataset
# to remove null values
df=df.dropna()
print(df)
# fill missing values with mean /median
df["Age"]=df["Age"].fillna(df["Age"].mean())
print(df[["Age"]])
print(df.duplicated())  # to find if duplicate values exist
print(df.duplicated().sum())  # to find sum of duplicate values
# remove duplicate values
df=df.drop_duplicates()
print(df.duplicated().sum())
#nsort values
df=df.sort_values("Marks")
print(df)
# sort in descending order
df=df.sort_values("Marks",ascending=False)
print(df)
# reset index
df=df.reset_index(drop=True)
print(df)
# rename columns
df=df.rename(columns={"Hours":"STUDYHOURS"})
print(df.columns)

In [ ]:
# practice 1
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E", "E"],
    "Age": [20, 21, None, 22, 20, 20],
    "Hours": [2, 4, 5, None, 8, 8],
    "Marks": [40, 50, 55, 70, None, None]
}

df = pd.DataFrame(data)
print(df)
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())
# practice 2
print(df.isnull())
print(df.isnull().sum())
# practice 3
df["Age"]=df["Age"].fillna(df["Age"].mean())
print(df.isnull().sum())
df["Hours"]=df["Hours"].fillna(df["Hours"].mean())
print(df.isnull().sum())
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())
print(df.isnull().sum())
# practice 4
print(df.duplicated())
df=df.drop_duplicates()
print(df.duplicated())